ln -fs ~/dotfiles/alacritty ~/.config/alacritty
ln -fs ~/dotfiles/electron-flags ~/.config/electron-flags
ln -fs ~/dotfiles/fontconfig ~/.config/fontconfig
ln -fs ~/dotfiles/kitty ~/.config/kitty
ln -fs ~/dotfiles/neofetch ~/.config/neofetch
ln -fs ~/dotfiles/npmrc ~/.npmrc
ln -fs ~/dotfiles/ranger ~/.config/ranger
ln -fs ~/dotfiles/sway ~/.config/sway
ln -fs ~/dotfiles/waybar ~/.config/waybar
ln -fs ~/dotfiles/zshenv ~/.zshenv
ln -fs ~/dotfiles/zshrc ~/.zshrc
